eriktks/conll2003:
  - O
  - B-PER
  - I-PER
  - B-ORG
  - I-ORG
  - B-LOC
  - I-LOC
  - B-MISC
  - I-MISC

eesuhn/crossner-ai:
  - O
  - B-field
  - I-field
  - B-task
  - I-task
  - B-product
  - I-product
  - B-algorithm
  - I-algorithm
  - B-researcher
  - I-researcher
  - B-metrics
  - I-metrics
  - B-programlang
  - I-programlang
  - B-conference
  - I-conference
  - B-university
  - I-university
  - B-country
  - I-country
  - B-person
  - I-person
  - B-organisation
  - I-organisation
  - B-location
  - I-location
  - B-misc
  - I-misc

eesuhn/crossner-literature:
  - O
  - B-book
  - I-book
  - B-writer
  - I-writer
  - B-award
  - I-award
  - B-poem
  - I-poem
  - B-event
  - I-event
  - B-magazine
  - I-magazine
  - B-literarygenre
  - I-literarygenre
  - B-country
  - I-country
  - B-person
  - I-person
  - B-location
  - I-location
  - B-organisation
  - I-organisation
  - B-misc
  - I-misc

eesuhn/crossner-science:
  - O
  - B-scientist
  - I-scientist
  - B-person
  - I-person
  - B-university
  - I-university
  - B-organisation
  - I-organisation
  - B-country
  - I-country
  - B-location
  - I-location
  - B-discipline
  - I-discipline
  - B-enzyme
  - I-enzyme
  - B-protein
  - I-protein
  - B-chemicalelement
  - I-chemicalelement
  - B-chemicalcompound
  - I-chemicalcompound
  - B-astronomicalobject
  - I-astronomicalobject
  - B-academicjournal
  - I-academicjournal
  - B-event
  - I-event
  - B-theory
  - I-theory
  - B-award
  - I-award
  - B-misc
  - I-misc
