dataset_labels:
  - DFKI-SLT/few-nerd:
      - "O"
      - "organization"
      - "location"
      - "person"
      - "other"
      - "building"
      - "product"
      - "art"
      - "event"
  - eriktks/conll2003:
      - "O"
      - "B-LOC"
      - "B-PER"
      - "B-ORG"
      - "I-PER"
      - "I-ORG"
      - "B-MISC"
      - "I-MISC"
      - "I-LOC"
