_wandb:
    value:
        cli_version: 0.21.0
        e:
            fbmcro3jx1lspo02atguyloetg8im7q6:
                args:
                    - --mode
                    - new
                    - --use-wandb
                    - --upload-model-wandb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "1081101176832"
                        used: "99337912320"
                email: eason.yihong@gmail.com
                executable: /home/yilim/kairo-core/.venv/bin/python3
                git:
                    commit: a686883a606cbd4bb378ed550cf9e67fa925c3ab
                    remote: https://github.com/eesuhn/kairo-core.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-d2835a95-6a4b-4458-0ff0-1fb346927c07
                host: DESKTOP-QO9VCS5
                memory:
                    total: "25204797440"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: -m scripts.train.ner
                python: CPython 3.11.13
                root: /home/yilim/kairo-core/reports/ner
                startedAt: "2025-07-24T04:13:24.317499Z"
                writerId: fbmcro3jx1lspo02atguyloetg8im7q6
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.45.2
            "12": 0.21.0
            "13": linux-x86_64
base_model_name:
    value: google-bert/bert-base-uncased
batch_size:
    value: 32
checkpoint_dir:
    value: /home/yilim/kairo-core/models/ner/checkpoints
device:
    value: cuda
dropout_rate:
    value: 0.1
early_stopping_delta:
    value: 0.001
early_stopping_patience:
    value: 3
epochs:
    value: 10
eval_steps:
    value: 500
freeze_bert:
    value: false
freeze_bert_encoder:
    value: false
ignore_index:
    value: -100
learning_rate:
    value: 0.0001
logging_steps:
    value: 100
max_grad_norm:
    value: 1
max_length:
    value: 128
model_dir:
    value: /home/yilim/kairo-core/models/ner
num_workers:
    value: 8
save_steps:
    value: 1000
seed:
    value: 42
upload_model_wandb:
    value: true
use_wandb:
    value: true
warmup_steps:
    value: 500
weight_decay:
    value: 0.01
