ner:
  - name: DFKI-SLT/few-nerd
    config: supervised
  - name: eriktks/conll2003
  - name: eesuhn/crossner-ai
  - name: eesuhn/crossner-science
  - name: eesuhn/crossner-literature

# summary:
#   - name: allenai/scitldr
#   - name: midas/semeval2017
