ner:
  - name: eriktks/conll2003
  - name: eesuhn/crossner-ai
  - name: eesuhn/crossner-science
  - name: eesuhn/crossner-literature

summary:
  # - name: allenai/scitldr
  #   config: Abstract
  # - name: csebuetnlp/xlsum
  #   config: english
  - name: sobamchan/aclsum
    config: extractive
    dir: sobamchan/aclsum-extractive
  - name: sobamchan/aclsum
    config: abstractive
    dir: sobamchan/aclsum-abstractive
