new_academic_labels:
  - "THEORY"
  - "METHOD"
  - "ALGORITHM"
  - "TECHNIQUE"
  - "DATASET"
  - "MODEL"
  - "FRAMEWORK"
  - "METRIC"
  - "EVALUATION"
  - "EXPERIMENT"
  - "HYPOTHESIS"
  - "CONCEPT"
  - "FINDING"
  - "RESULT"
  - "CONCLUSION"
  - "CONTRIBUTION"
  - "LIMITATION"
  - "FUTURE_WORK"
  - "RESEARCH_QUESTION"
  - "VARIABLE"
  - "PARAMETER"
  - "BASELINE"
  - "BENCHMARK"
  - "TOOL"
  - "SOFTWARE"
  - "LIBRARY"
  - "CITATION"
  - "AUTHOR"
  - "PUBLICATION"
  - "VENUE"
