repos:
  - repo: local
    hooks:
      - id: nb-clean
        name: "nb-clean clean notebooks/"
        entry: uv
        language: system
        args: ["run", "nb-clean", "clean", "notebooks"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: true

      - id: ruff-format
        name: "ruff format"
        entry: uv
        language: system
        args: ["run", "ruff", "format"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: true

      - id: ruff-check
        name: "ruff check --fix"
        entry: uv
        language: system
        args: ["run", "ruff", "check", "--fix"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
