repos:
  - repo: local
    hooks:
      - id: nb-update
        name: "Custom scripts/ for notebooks/"
        entry: uv
        language: system
        args: ["run", "-m", "scripts.nb.main"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: false
        files: '^notebooks/.*\.ipynb$'

      - id: nb-clean
        name: "Cleaning notebooks"
        entry: uv
        language: system
        args: ["run", "nb-clean", "clean", "-n", "notebooks/"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: false
        files: '^notebooks/.*\.ipynb$'

      - id: ruff-format
        name: "Format with ruff"
        entry: uv
        language: system
        args: ["run", "ruff", "format"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: true

      - id: ruff-check
        name: "Check (Fix) with ruff"
        entry: uv
        language: system
        args: ["run", "ruff", "check", "--fix"]
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
